FROM denoland/deno:2.1.4

ARG UID
ARG GID
ENV UID=$UID
ENV GID=$GID
RUN groupmod -g $GID || true
RUN usermod -u $UID -g $GID deno

WORKDIR /usr/src/app

EXPOSE 3000/tcp

# Run as deno user to generate node_modules with correct permissions
USER deno

CMD ["sleep", "infinity"]
