FROM denoland/deno:2.1.4

WORKDIR /usr/src/app

EXPOSE 3000/tcp

# Change the folder permission
RUN chown -R deno:deno /usr/src/app

# Copy the files to the working directory
COPY . .

# Install dependencies
RUN deno install --allow-scripts=npm:@sveltejs/kit@2.15.2

ENTRYPOINT [ "deno", "run", "dev" ]
