services:

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    restart: unless-stopped

  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    restart: unless-stopped

  backend:
    build:
      context: ./backend/
    environment:
      - PORT=8080
    volumes:
      - ./backend:/app
    ports:
      - "8081:8080"
    restart: unless-stopped
