services:

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - ./frontend/node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3000"
    restart: unless-stopped

  backend:
    build:
      context: ./backend/
    environment:
      - PORT=8080
    volumes:
      - ./backend:/app
    ports:
      - "8081:8080"
    restart: unless-stopped
