linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asciicheck
    - bodyclose

issues:
  exclude-dirs:
    - sherpa-onnx/*
  exclude-files:
    - webrtcServer/sherpa.go # Opus is needed for golangci-lint to work
