http:
  routers:
    frontend-router-http:
      rule: "Host(`ai-clean-chat.home.site`)"  # Match the hostname
      entryPoints:
        - web
      service: frontend-service

    backend-router-http:
      rule: "Host(`ai-clean-chat.home.site`) && PathPrefix(`/api/backend/`)"  # Match the API path
      entryPoints:
        - web
      service: backend-service

    frontend-router-https:
      rule: "Host(`ai-clean-chat.home.site`)"  # Match the hostname
      entryPoints:
        - websecure
      service: frontend-service
      tls: true

    backend-router-https:
      rule: "Host(`ai-clean-chat.home.site`) && PathPrefix(`/api/backend/`)"  # Match the API path
      entryPoints:
        - websecure
      service: backend-service
      middlewares:
        - strip-api-prefix
      tls: true

  services:
    frontend-service:
      loadBalancer:
        servers:
          - url: "http://frontend:3000"

    backend-service:
      loadBalancer:
        servers:
          - url: "http://backend:8080"
        passHostHeader: true  # Ensures Host header is passed to backend

  middlewares:
    strip-api-prefix:
      stripPrefix:
        prefixes:
          - "/api/backend"
tls:
  certificates:
    - certFile: /var/traefik/certs/ai-clean-chat.home.site.pem
      keyFile: /var/traefik/certs/ai-clean-chat.home.site-key.pem
