http:
  routers:
    frontend-router-http:
      rule: "Host(`ai-clean-chat.home.site`)"
      entryPoints:
        - web
      service: frontend-service

    frontend-router-https:
      rule: "Host(`ai-clean-chat.home.site`)"
      entryPoints:
        - websecure
      service: frontend-service
      tls: true

    backend-router-http:
      rule: "Host(`ai-clean-chat.home.site`) && PathPrefix(`/api/backend/`)"
      entryPoints:
        - web
      service: backend-service

    backend-router-https:
      rule: "Host(`ai-clean-chat.home.site`) && PathPrefix(`/api/backend/`)"
      entryPoints:
        - websecure
      service: backend-service
      middlewares:
        - strip-api-prefix
      tls: true

    profanity-router-http:
      rule: "Host(`ai-clean-chat.home.site`) && PathPrefix(`/api/profanity/`)"
      entryPoints:
        - web
      service: profanity-service

    profanity-router-https:
      rule: "Host(`ai-clean-chat.home.site`) && PathPrefix(`/api/profanity/`)"
      entryPoints:
        - websecure
      service: profanity-service
      middlewares:
        - strip-profanity-prefix
      tls: true

  services:
    frontend-service:
      loadBalancer:
        servers:
          - url: "http://frontend:3000"

    backend-service:
      loadBalancer:
        servers:
          - url: "http://backend:8080"
        passHostHeader: true

    profanity-service:
      loadBalancer:
        servers:
          - url: "http://profanity:8080"
        passHostHeader: true

  middlewares:
    strip-api-prefix:
      stripPrefix:
        prefixes:
          - "/api/backend"
    strip-profanity-prefix:
      stripPrefix:
        prefixes:
          - "/api/profanity"
tls:
  certificates:
    - certFile: /var/traefik/certs/ai-clean-chat.home.site.pem
      keyFile: /var/traefik/certs/ai-clean-chat.home.site-key.pem
